In [1]:
import pandas as pd
import numpy as np
import pymysql
from sqlalchemy import create_engine

In [9]:
df=pd.read_excel("Nashville Housing Data for Data Cleaning.xlsx", parse_dates=['SaleDate'])

In [9]:
df.head()

,UniqueID,ParcelID,LandUse,PropertyAddress,SaleDate,SalePrice,LegalReference,SoldAsVacant,OwnerName,OwnerAddress,Acreage,TaxDistrict,LandValue,BuildingValue,TotalValue,YearBuilt,Bedrooms,FullBath,HalfBath
0,2045,007 00 0 125.00,SINGLE FAMILY,"1808 FOX CHASE DR, GOODLETTSVILLE",2013-04-09,240000,20130412-0036474,No,"FRAZIER, CYRENTHA LYNETTE","1808 FOX CHASE DR, GOODLETTSVILLE, TN",2.3,GENERAL SERVICES DISTRICT,50000.0,168200.0,235700.0,1986.0,3.0,3.0,0.0
1,16918,007 00 0 130.00,SINGLE FAMILY,"1832 FOX CHASE DR, GOODLETTSVILLE",2014-06-10,366000,20140619-0053768,No,"BONER, CHARLES & LESLIE","1832 FOX CHASE DR, GOODLETTSVILLE, TN",3.5,GENERAL SERVICES DISTRICT,50000.0,264100.0,319000.0,1998.0,3.0,3.0,2.0
2,54582,007 00 0 138.00,SINGLE FAMILY,"1864 FOX CHASE DR, GOODLETTSVILLE",2016-09-26,435000,20160927-0101718,No,"WILSON, JAMES E. & JOANNE","1864 FOX CHASE DR, GOODLETTSVILLE, TN",2.9,GENERAL SERVICES DISTRICT,50000.0,216200.0,298000.0,1987.0,4.0,3.0,0.0
3,43070,007 00 0 143.00,SINGLE FAMILY,"1853 FOX CHASE DR, GOODLETTSVILLE",2016-01-29,255000,20160129-0008913,No,"BAKER, JAY K. & SUSAN E.","1853 FOX CHASE DR, GOODLETTSVILLE, TN",2.6,GENERAL SERVICES DISTRICT,50000.0,147300.0,197300.0,1985.0,3.0,3.0,0.0
4,22714,007 00 0 149.00,SINGLE FAMILY,"1829 FOX CHASE DR, GOODLETTSVILLE",2014-10-10,278000,20141015-0095255,No,"POST, CHRISTOPHER M. & SAMANTHA C.","1829 FOX CHASE DR, GOODLETTSVILLE, TN",2.0,GENERAL SERVICES DISTRICT,50000.0,152300.0,202300.0,1984.0,4.0,3.0,0.0

In [4]:
df.dtypes

UniqueID                    int64
ParcelID                   object
LandUse                    object
PropertyAddress            object
SaleDate           datetime64[ns]
SalePrice                   int64
LegalReference             object
SoldAsVacant               object
OwnerName                  object
OwnerAddress               object
Acreage                   float64
TaxDistrict                object
LandValue                 float64
BuildingValue             float64
TotalValue                float64
YearBuilt                 float64
Bedrooms                  float64
FullBath                  float64
HalfBath                  float64
dtype: object

In [30]:
df.iloc[[159,223]]

,UniqueID,ParcelID,LandUse,PropertyAddress,SaleDate,SalePrice,LegalReference,SoldAsVacant,OwnerName,OwnerAddress,Acreage,TaxDistrict,LandValue,BuildingValue,TotalValue,YearBuilt,Bedrooms,FullBath,HalfBath
159,43076,025 07 0 031.00,SINGLE FAMILY,NaN,2016-01-15,179900,20160120-0005776,No,"COSTNER, FRED & CAROLYN","410 ROSEHILL CT, GOODLETTSVILLE, TN",0.96,CITY OF GOODLETTSVILLE,30000.0,70000.0,100000.0,1964.0,3.0,1.0,0.0
223,39432,026 01 0 069.00,VACANT RESIDENTIAL LAND,NaN,2015-10-23,153000,20151028-0109602,No,"SHACKLEFORD, MICHAEL C., JR.","141 TWO MILE PIKE, GOODLETTSVILLE, TN",0.17,CITY OF GOODLETTSVILLE,21100.0,121600.0,142700.0,2015.0,3.0,2.0,0.0

In [53]:
xxx=df['PropertyAddress'].isna()
xxx

0        False
1        False
2        False
3        False
4        False
         ...
56472    False
56473    False
56474    False
56475    False
56476    False
Name: PropertyAddress, Length: 56477, dtype: bool

In [54]:
xxx.sum()

29

In [85]:
# replace n and y by no and yes
df['SoldAsVacant'].replace({'N':'No', 'Y':'Yes'})

0         No
1         No
2         No
3         No
4         No
        ...
56472     No
56473     No
56474    Yes
56475    Yes
56476    Yes
Name: SoldAsVacant, Length: 56477, dtype: object

In [11]:
df.columns=df.columns.str.strip()
df.columns

Index(['UniqueID', 'ParcelID', 'LandUse', 'PropertyAddress', 'SaleDate',
       'SalePrice', 'LegalReference', 'SoldAsVacant', 'OwnerName',
       'OwnerAddress', 'Acreage', 'TaxDistrict', 'LandValue', 'BuildingValue',
       'TotalValue', 'YearBuilt', 'Bedrooms', 'FullBath', 'HalfBath'],
      dtype='object')

In [13]:
df.set_index('UniqueID',inplace=True)

In [19]:
# remove duplicates
df.duplicated()

102

In [27]:
xxx=df.drop_duplicates()
xxx.shape

(56375, 18)

In [71]:
xxx

,ParcelID,LandUse,PropertyAddress,SaleDate,SalePrice,LegalReference,SoldAsVacant,OwnerName,OwnerAddress,Acreage,TaxDistrict,LandValue,BuildingValue,TotalValue,YearBuilt,Bedrooms,FullBath,HalfBath,Split_Address
UniqueID,,,,,,,,,,,,,,,,,,,
2045,007 00 0 125.00,SINGLE FAMILY,"1808 FOX CHASE DR, GOODLETTSVILLE",2013-04-09,240000,20130412-0036474,No,"FRAZIER, CYRENTHA LYNETTE","1808 FOX CHASE DR, GOODLETTSVILLE, TN",2.3,GENERAL SERVICES DISTRICT,50000.0,168200.0,235700.0,1986.0,3.0,3.0,0.0,1808 FOX CHASE DR
16918,007 00 0 130.00,SINGLE FAMILY,"1832 FOX CHASE DR, GOODLETTSVILLE",2014-06-10,366000,20140619-0053768,No,"BONER, CHARLES & LESLIE","1832 FOX CHASE DR, GOODLETTSVILLE, TN",3.5,GENERAL SERVICES DISTRICT,50000.0,264100.0,319000.0,1998.0,3.0,3.0,2.0,1832 FOX CHASE DR
54582,007 00 0 138.00,SINGLE FAMILY,"1864 FOX CHASE DR, GOODLETTSVILLE",2016-09-26,435000,20160927-0101718,No,"WILSON, JAMES E. & JOANNE","1864 FOX CHASE DR, GOODLETTSVILLE, TN",2.9,GENERAL SERVICES DISTRICT,50000.0,216200.0,298000.0,1987.0,4.0,3.0,0.0,1864 FOX CHASE DR
43070,007 00 0 143.00,SINGLE FAMILY,"1853 FOX CHASE DR, GOODLETTSVILLE",2016-01-29,255000,20160129-0008913,No,"BAKER, JAY K. & SUSAN E.","1853 FOX CHASE DR, GOODLETTSVILLE, TN",2.6,GENERAL SERVICES DISTRICT,50000.0,147300.0,197300.0,1985.0,3.0,3.0,0.0,1853 FOX CHASE DR
22714,007 00 0 149.00,SINGLE FAMILY,"1829 FOX CHASE DR, GOODLETTSVILLE",2014-10-10,278000,20141015-0095255,No,"POST, CHRISTOPHER M. & SAMANTHA C.","1829 FOX CHASE DR, GOODLETTSVILLE, TN",2.0,GENERAL SERVICES DISTRICT,50000.0,152300.0,202300.0,1984.0,4.0,3.0,0.0,1829 FOX CHASE DR
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30469,188 10 0A 101.00,SINGLE FAMILY,"1435 WINDING CREEK DR, NOLENSVILLE",2015-05-27,157500,20150608-0053286,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27707,188 10 0A 107.00,SINGLE FAMILY,"1423 WINDING CREEK DR, NOLENSVILLE",2015-03-02,145000,20150304-0019013,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
52709,188 10 0A 118.00,VACANT RESIDENTIAL LAND,"1804 GRACE POINT LN, NOLENSVILLE",2016-08-16,234611,20160819-0087214,Yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
54042,188 10 0A 121.00,VACANT RESIDENTIAL LAND,"1709 PARK TERRACE LN, NOLENSVILLE",2016-09-07,93844,20160919-0098411,Yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
54043,188 10 0A 122.00,VACANT RESIDENTIAL LAND,"1713 PARK TERRACE LN, NOLENSVILLE",2016-09-07,93844,20160919-0098411,Yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [77]:
#  chop address to multiple columns
yyy=xxx['OwnerAddress'].str.split(pat=',', expand=True)
yyy.columns=['address','city','state']
#xxx.loc[:,'Split_Address']=yyy['address']
xxx.insert(3,"Split_Address",yyy['address'])
xxx

,ParcelID,LandUse,PropertyAddress,Split_Address,SaleDate,SalePrice,LegalReference,SoldAsVacant,OwnerName,OwnerAddress,Acreage,TaxDistrict,LandValue,BuildingValue,TotalValue,YearBuilt,Bedrooms,FullBath,HalfBath
UniqueID,,,,,,,,,,,,,,,,,,,
2045,007 00 0 125.00,SINGLE FAMILY,"1808 FOX CHASE DR, GOODLETTSVILLE",1808 FOX CHASE DR,2013-04-09,240000,20130412-0036474,No,"FRAZIER, CYRENTHA LYNETTE","1808 FOX CHASE DR, GOODLETTSVILLE, TN",2.3,GENERAL SERVICES DISTRICT,50000.0,168200.0,235700.0,1986.0,3.0,3.0,0.0
16918,007 00 0 130.00,SINGLE FAMILY,"1832 FOX CHASE DR, GOODLETTSVILLE",1832 FOX CHASE DR,2014-06-10,366000,20140619-0053768,No,"BONER, CHARLES & LESLIE","1832 FOX CHASE DR, GOODLETTSVILLE, TN",3.5,GENERAL SERVICES DISTRICT,50000.0,264100.0,319000.0,1998.0,3.0,3.0,2.0
54582,007 00 0 138.00,SINGLE FAMILY,"1864 FOX CHASE DR, GOODLETTSVILLE",1864 FOX CHASE DR,2016-09-26,435000,20160927-0101718,No,"WILSON, JAMES E. & JOANNE","1864 FOX CHASE DR, GOODLETTSVILLE, TN",2.9,GENERAL SERVICES DISTRICT,50000.0,216200.0,298000.0,1987.0,4.0,3.0,0.0
43070,007 00 0 143.00,SINGLE FAMILY,"1853 FOX CHASE DR, GOODLETTSVILLE",1853 FOX CHASE DR,2016-01-29,255000,20160129-0008913,No,"BAKER, JAY K. & SUSAN E.","1853 FOX CHASE DR, GOODLETTSVILLE, TN",2.6,GENERAL SERVICES DISTRICT,50000.0,147300.0,197300.0,1985.0,3.0,3.0,0.0
22714,007 00 0 149.00,SINGLE FAMILY,"1829 FOX CHASE DR, GOODLETTSVILLE",1829 FOX CHASE DR,2014-10-10,278000,20141015-0095255,No,"POST, CHRISTOPHER M. & SAMANTHA C.","1829 FOX CHASE DR, GOODLETTSVILLE, TN",2.0,GENERAL SERVICES DISTRICT,50000.0,152300.0,202300.0,1984.0,4.0,3.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30469,188 10 0A 101.00,SINGLE FAMILY,"1435 WINDING CREEK DR, NOLENSVILLE",NaN,2015-05-27,157500,20150608-0053286,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27707,188 10 0A 107.00,SINGLE FAMILY,"1423 WINDING CREEK DR, NOLENSVILLE",NaN,2015-03-02,145000,20150304-0019013,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
52709,188 10 0A 118.00,VACANT RESIDENTIAL LAND,"1804 GRACE POINT LN, NOLENSVILLE",NaN,2016-08-16,234611,20160819-0087214,Yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
54042,188 10 0A 121.00,VACANT RESIDENTIAL LAND,"1709 PARK TERRACE LN, NOLENSVILLE",NaN,2016-09-07,93844,20160919-0098411,Yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
54043,188 10 0A 122.00,VACANT RESIDENTIAL LAND,"1713 PARK TERRACE LN, NOLENSVILLE",NaN,2016-09-07,93844,20160919-0098411,Yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [87]:
xxx.drop(columns=['Split_Address'], inplace=True)

KeyError: "['Split_Address'] not found in axis"

In [88]:
xxx

,ParcelID,LandUse,PropertyAddress,SaleDate,SalePrice,LegalReference,SoldAsVacant,OwnerName,OwnerAddress,Acreage,TaxDistrict,LandValue,BuildingValue,TotalValue,YearBuilt,Bedrooms,FullBath,HalfBath
UniqueID,,,,,,,,,,,,,,,,,,
2045,007 00 0 125.00,SINGLE FAMILY,"1808 FOX CHASE DR, GOODLETTSVILLE",2013-04-09,240000,20130412-0036474,No,"FRAZIER, CYRENTHA LYNETTE","1808 FOX CHASE DR, GOODLETTSVILLE, TN",2.3,GENERAL SERVICES DISTRICT,50000.0,168200.0,235700.0,1986.0,3.0,3.0,0.0
16918,007 00 0 130.00,SINGLE FAMILY,"1832 FOX CHASE DR, GOODLETTSVILLE",2014-06-10,366000,20140619-0053768,No,"BONER, CHARLES & LESLIE","1832 FOX CHASE DR, GOODLETTSVILLE, TN",3.5,GENERAL SERVICES DISTRICT,50000.0,264100.0,319000.0,1998.0,3.0,3.0,2.0
54582,007 00 0 138.00,SINGLE FAMILY,"1864 FOX CHASE DR, GOODLETTSVILLE",2016-09-26,435000,20160927-0101718,No,"WILSON, JAMES E. & JOANNE","1864 FOX CHASE DR, GOODLETTSVILLE, TN",2.9,GENERAL SERVICES DISTRICT,50000.0,216200.0,298000.0,1987.0,4.0,3.0,0.0
43070,007 00 0 143.00,SINGLE FAMILY,"1853 FOX CHASE DR, GOODLETTSVILLE",2016-01-29,255000,20160129-0008913,No,"BAKER, JAY K. & SUSAN E.","1853 FOX CHASE DR, GOODLETTSVILLE, TN",2.6,GENERAL SERVICES DISTRICT,50000.0,147300.0,197300.0,1985.0,3.0,3.0,0.0
22714,007 00 0 149.00,SINGLE FAMILY,"1829 FOX CHASE DR, GOODLETTSVILLE",2014-10-10,278000,20141015-0095255,No,"POST, CHRISTOPHER M. & SAMANTHA C.","1829 FOX CHASE DR, GOODLETTSVILLE, TN",2.0,GENERAL SERVICES DISTRICT,50000.0,152300.0,202300.0,1984.0,4.0,3.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30469,188 10 0A 101.00,SINGLE FAMILY,"1435 WINDING CREEK DR, NOLENSVILLE",2015-05-27,157500,20150608-0053286,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27707,188 10 0A 107.00,SINGLE FAMILY,"1423 WINDING CREEK DR, NOLENSVILLE",2015-03-02,145000,20150304-0019013,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
52709,188 10 0A 118.00,VACANT RESIDENTIAL LAND,"1804 GRACE POINT LN, NOLENSVILLE",2016-08-16,234611,20160819-0087214,Yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
54042,188 10 0A 121.00,VACANT RESIDENTIAL LAND,"1709 PARK TERRACE LN, NOLENSVILLE",2016-09-07,93844,20160919-0098411,Yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
54043,188 10 0A 122.00,VACANT RESIDENTIAL LAND,"1713 PARK TERRACE LN, NOLENSVILLE",2016-09-07,93844,20160919-0098411,Yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [91]:
xxx.insert(3,'Split_Address',yyy['address'])

ValueError: cannot insert Split_Address, already exists

In [92]:
xxx

,ParcelID,LandUse,PropertyAddress,Split_Address,SaleDate,SalePrice,LegalReference,SoldAsVacant,OwnerName,OwnerAddress,Acreage,TaxDistrict,LandValue,BuildingValue,TotalValue,YearBuilt,Bedrooms,FullBath,HalfBath
UniqueID,,,,,,,,,,,,,,,,,,,
2045,007 00 0 125.00,SINGLE FAMILY,"1808 FOX CHASE DR, GOODLETTSVILLE",1808 FOX CHASE DR,2013-04-09,240000,20130412-0036474,No,"FRAZIER, CYRENTHA LYNETTE","1808 FOX CHASE DR, GOODLETTSVILLE, TN",2.3,GENERAL SERVICES DISTRICT,50000.0,168200.0,235700.0,1986.0,3.0,3.0,0.0
16918,007 00 0 130.00,SINGLE FAMILY,"1832 FOX CHASE DR, GOODLETTSVILLE",1832 FOX CHASE DR,2014-06-10,366000,20140619-0053768,No,"BONER, CHARLES & LESLIE","1832 FOX CHASE DR, GOODLETTSVILLE, TN",3.5,GENERAL SERVICES DISTRICT,50000.0,264100.0,319000.0,1998.0,3.0,3.0,2.0
54582,007 00 0 138.00,SINGLE FAMILY,"1864 FOX CHASE DR, GOODLETTSVILLE",1864 FOX CHASE DR,2016-09-26,435000,20160927-0101718,No,"WILSON, JAMES E. & JOANNE","1864 FOX CHASE DR, GOODLETTSVILLE, TN",2.9,GENERAL SERVICES DISTRICT,50000.0,216200.0,298000.0,1987.0,4.0,3.0,0.0
43070,007 00 0 143.00,SINGLE FAMILY,"1853 FOX CHASE DR, GOODLETTSVILLE",1853 FOX CHASE DR,2016-01-29,255000,20160129-0008913,No,"BAKER, JAY K. & SUSAN E.","1853 FOX CHASE DR, GOODLETTSVILLE, TN",2.6,GENERAL SERVICES DISTRICT,50000.0,147300.0,197300.0,1985.0,3.0,3.0,0.0
22714,007 00 0 149.00,SINGLE FAMILY,"1829 FOX CHASE DR, GOODLETTSVILLE",1829 FOX CHASE DR,2014-10-10,278000,20141015-0095255,No,"POST, CHRISTOPHER M. & SAMANTHA C.","1829 FOX CHASE DR, GOODLETTSVILLE, TN",2.0,GENERAL SERVICES DISTRICT,50000.0,152300.0,202300.0,1984.0,4.0,3.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30469,188 10 0A 101.00,SINGLE FAMILY,"1435 WINDING CREEK DR, NOLENSVILLE",NaN,2015-05-27,157500,20150608-0053286,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27707,188 10 0A 107.00,SINGLE FAMILY,"1423 WINDING CREEK DR, NOLENSVILLE",NaN,2015-03-02,145000,20150304-0019013,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
52709,188 10 0A 118.00,VACANT RESIDENTIAL LAND,"1804 GRACE POINT LN, NOLENSVILLE",NaN,2016-08-16,234611,20160819-0087214,Yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
54042,188 10 0A 121.00,VACANT RESIDENTIAL LAND,"1709 PARK TERRACE LN, NOLENSVILLE",NaN,2016-09-07,93844,20160919-0098411,Yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
54043,188 10 0A 122.00,VACANT RESIDENTIAL LAND,"1713 PARK TERRACE LN, NOLENSVILLE",NaN,2016-09-07,93844,20160919-0098411,Yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [56]:
df.loc[df['PropertyAddress'].isna()]

,UniqueID,ParcelID,LandUse,PropertyAddress,SaleDate,SalePrice,LegalReference,SoldAsVacant,OwnerName,OwnerAddress,Acreage,TaxDistrict,LandValue,BuildingValue,TotalValue,YearBuilt,Bedrooms,FullBath,HalfBath
159,43076,025 07 0 031.00,SINGLE FAMILY,NaN,2016-01-15,179900,20160120-0005776,No,"COSTNER, FRED & CAROLYN","410 ROSEHILL CT, GOODLETTSVILLE, TN",0.96,CITY OF GOODLETTSVILLE,30000.0,70000.0,100000.0,1964.0,3.0,1.0,0.0
223,39432,026 01 0 069.00,VACANT RESIDENTIAL LAND,NaN,2015-10-23,153000,20151028-0109602,No,"SHACKLEFORD, MICHAEL C., JR.","141 TWO MILE PIKE, GOODLETTSVILLE, TN",0.17,CITY OF GOODLETTSVILLE,21100.0,121600.0,142700.0,2015.0,3.0,2.0,0.0
246,45290,026 05 0 017.00,SINGLE FAMILY,NaN,2016-03-29,155000,20160330-0029941,No,"TRIPP, MARVIN S. & DEBORAH YOUNG","208 EAST AVE, GOODLETTSVILLE, TN",0.20,CITY OF GOODLETTSVILLE,21100.0,130200.0,151300.0,2008.0,3.0,2.0,0.0
305,53147,026 06 0A 038.00,RESIDENTIAL CONDO,NaN,2016-08-25,144900,20160831-0091567,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
531,43080,033 06 0 041.00,SINGLE FAMILY,NaN,2016-01-04,170000,20160107-0001526,No,"FRANK, ZACHARY & NIKI","1129 CAMPBELL RD, GOODLETTSVILLE, TN",0.24,GENERAL SERVICES DISTRICT,35000.0,110500.0,145500.0,2000.0,3.0,2.0,0.0
533,45295,033 06 0A 002.00,SINGLE FAMILY,NaN,2016-03-29,210000,20160331-0030709,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
665,48731,033 15 0 123.00,SINGLE FAMILY,NaN,2016-05-05,199900,20160506-0045368,No,"COLEMAN, AARON A. & CECIL, CORRIE J.","438 W CAMPBELL RD, GOODLETTSVILLE, TN",1.39,GENERAL SERVICES DISTRICT,45000.0,90300.0,135300.0,1954.0,2.0,1.0,0.0
858,36531,034 03 0 059.00,SINGLE FAMILY,NaN,2015-08-13,245000,20150819-0083759,No,"DILICK, JOHN MARK & ANNETTE A.","2117 PAULA DR, MADISON, TN",1.01,GENERAL SERVICES DISTRICT,32000.0,170000.0,228300.0,1964.0,4.0,3.0,0.0
1043,46919,034 07 0B 015.00,VACANT RESIDENTIAL LAND,NaN,2016-04-27,40000,20160304-0020905,Yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1176,44264,034 16 0A 004.00,VACANT RESIDENTIAL LAND,NaN,2016-02-04,130000,20160205-0011327,Yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1262,45298,041 03 0A 100.00,SINGLE FAMILY,NaN,2016-03-18,170000,20160322-0027048,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1642,40678,042 13 0 075.00,SINGLE FAMILY,NaN,2015-11-30,208000,20151209-0123831,No,"SADOWSKY, ERIC C. & LISA D.","222 FOXBORO DR, MADISON, TN",1.01,GENERAL SERVICES DISTRICT,30000.0,100000.0,130000.0,1967.0,3.0,1.0,1.0
1782,47293,043 04 0 014.00,SINGLE FAMILY,NaN,2016-04-29,190000,20160503-0043576,No,"CRIPPS, WILLIE S. JR. & GINEA M.","112 HILLER DR, OLD HICKORY, TN",0.29,GENERAL SERVICES DISTRICT,17000.0,143700.0,173600.0,1956.0,4.0,2.0,1.0
1921,22775,043 09 0 074.00,VACANT RESIDENTIAL LAND,NaN,2014-10-27,151000,20141028-0099094,Yes,"BREWER HOLDINGS, LLC","213 B LOVELL ST, MADISON, TN",0.15,GENERAL SERVICES DISTRICT,18000.0,115600.0,133600.0,2015.0,3.0,2.0,0.0
2110,45349,043 13 0 308.00,SINGLE FAMILY,NaN,2016-03-31,155000,20160405-0032445,No,"JACKSON, ADAM L. & MOORE, MARY A.","224 HICKORY ST, MADISON, TN",0.16,GENERAL SERVICES DISTRICT,16000.0,65900.0,81900.0,1940.0,2.0,1.0,0.0
2362,50927,044 05 0 135.00,SINGLE FAMILY,NaN,2016-06-15,160000,20160617-0061987,No,"SMITH, WARREN & MARTHA","202 KEETON AVE, OLD HICKORY, TN",0.12,GENERAL SERVICES DISTRICT,19000.0,102700.0,121700.0,2015.0,4.0,2.0,0.0
3434,3299,052 01 0 296.00,SINGLE FAMILY,NaN,2013-05-31,79370,20130620-0063114,No,"KIRBY, WILLIAM E. JR","726 IDLEWILD DR, MADISON, TN",0.22,GENERAL SERVICES DISTRICT,16000.0,60800.0,76800.0,1957.0,2.0,1.0,0.0
3681,43151,052 08 0A 320.00,SINGLE FAMILY,NaN,2016-01-15,150000,20160119-0004918,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19984,49886,092 06 0 273.00,SINGLE FAMILY,NaN,2016-06-21,186000,20160705-0068281,No,"SOLAVA, RACHEL LYNN","2721 HERMAN ST, NASHVILLE, TN",0.17,URBAN SERVICES DISTRICT,9000.0,63200.0,72200.0,1987.0,2.0,1.0,1.0
19986,27140,092 06 0 282.00,SINGLE FAMILY,NaN,2015-02-20,41500,20150224-0015900,No,PROSPERITAS PARTNERS LLC,"815 31ST AVE N, NASHVILLE, TN",0.17,URBAN SERVICES DISTRICT,13000.0,49400.0,62400.0,1960.0,2.0,1.0,0.0
20328,11478,092 13 0 322.00,SINGLE FAMILY,NaN,2014-01-17,269500,20140122-0006168,No,"WIGGINS, MATHEW L. & GOOD, KENDRA A.","237 37TH AVE N, NASHVILLE, TN",0.34,URBAN SERVICES DISTRICT,91000.0,107100.0,198100.0,1945.0,2.0,1.0,0.0
20332,32385,092 13 0 339.00,SINGLE FAMILY,NaN,2015-06-05,450000,20150618-0058311,No,"JUMPER, NICOLE","311 35TH AVE N, NASHVILLE, TN",0.16,URBAN SERVICES DISTRICT,65000.0,365300.0,430300.0,2015.0,3.0,3.0,1.0
21129,8126,093 08 0 054.00,SINGLE FAMILY,NaN,2013-09-20,25000,20130923-0099666,N,"CRAWFORD, CHRISTOPHER C. & BOBBIE LEANN","700 GLENVIEW DR, NASHVILLE, TN",0.21,URBAN SERVICES DISTRICT,25000.0,236800.0,261800.0,2015.0,3.0,2.0,1.0
29124,45774,107 13 0 107.00,SINGLE FAMILY,NaN,2016-03-28,169900,20160330-0030078,No,"GROOMS, MICAH & CASEY","1205 THOMPSON PL, NASHVILLE, TN",0.39,URBAN SERVICES DISTRICT,17000.0,75600.0,96200.0,1949.0,3.0,1.0,0.0
29332,14753,108 07 0A 026.00,RESIDENTIAL CONDO,NaN,2014-04-15,79900,20140416-0031777,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29894,15886,109 04 0A 080.00,VACANT RES LAND,NaN,2014-05-13,255590,20140514-0041276,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30087,24197,110 03 0A 061.00,SINGLE FAMILY,NaN,2014-11-19,269750,20141120-0106962,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30192,51930,113 14 0A 002.00,VACANT RESIDENTIAL LAND,NaN,2016-07-05,133000,20160707-0069375,Yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30540,51703,114 15 0A 030.00,RESIDENTIAL CONDO,NaN,2016-07-08,343235,20160713-0071757,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [21]:
df.shape

(56477, 18)

In [66]:
df.columns=df.columns.str.strip()  #Remove leading and trailing characters. If None then whitespaces are removed
df.columns

Index(['UniqueID', 'ParcelID', 'LandUse', 'PropertyAddress', 'SaleDate',
       'SalePrice', 'LegalReference', 'SoldAsVacant', 'OwnerName',
       'OwnerAddress', 'Acreage', 'TaxDistrict', 'LandValue', 'BuildingValue',
       'TotalValue', 'YearBuilt', 'Bedrooms', 'FullBath', 'HalfBath'],
      dtype='object')

In [69]:
conn=create_engine('mysql+pymysql://root:yxdj87212241@localhost/house_proj')
df.to_sql('house_data', conn, index=False, if_exists='replace')